# Generated by Django 5.0.7 on 2026-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_id_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='id_merged_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
    ]
