# Generated by Django 5.0.7 on 2026-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanapplication_id_merged_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincredential',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='payment_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='payment_receipt',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['email', 'submitted_at'], name='loans_loana_email_fff1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['payment_receipt'], name='loans_loana_payment_a7e3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['payment_checkout_id'], name='loans_loana_payment_fbc666_idx'),
        ),
    ]
